backend/pokerogue/src/main/java/com/pokerogue/helper/ability/domain/PokemonAbility.java, backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/ErrorMessage.java, backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/GlobalCustomException.java, backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/PokemonExceptionHandler.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/controller/PokemonController.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonAbilityMapping.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokedexResponse.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonRepository.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java, backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonTypeResponse.java
=> [BE_FEAT] 단일 포켓몬 정보 불러오는 API

.github/workflows/Backend-CD.yml, .github/workflows/Backend-CI.yml, backend/pokerogue/build.gradle, backend/pokerogue/docker/Dockerfile, backend/pokerogue/docker/Dockerfile-nginx, backend/pokerogue/docker/nginx/conf.d/nginx.conf
> Issue Number: #21
현재는 nginx와 springboot application만 docker로 띄웠는데 나중에 cerbot도 띄워서 ssl 인증서 발급 받는 것도 자동화하면 좋을 듯 합니다 😊 근데 지금은 힘들어서 안돼요 ..
설정 파일 (application.yml)이 좀 바뀌었는데 로컬에서 개발할 때는 `application-mysql.yml` 혹은 `application-h2.yml`을 사용해주세요!
=> [BE-FEAT] 개발 서버 배포

android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionBottomSheetFragment.kt, android/app/src/main/java/poke/rogue/helper/presentation/type/view/TypeChip.kt, android/app/src/main/java/poke/rogue/helper/presentation/type/view/TypeItemView.kt, android/app/src/main/java/poke/rogue/helper/presentation/util/BundleExtensions.kt, android/app/src/main/java/poke/rogue/helper/presentation/util/IntentExensions.kt, android/app/src/main/java/poke/rogue/helper/presentation/util/fragment/FragmentExtension.kt, android/app/src/main/java/poke/rogue/helper/presentation/util/view/CommonBindingAdapter.kt, android/app/src/main/res/layout/item_type.xml, android/app/src/main/res/layout/item_type_name.xml, android/app/src/main/res/values/attrs.xml, android/app/src/main/res/values/colors.xml, android/app/src/main/res/values/type.xml
- closed #35 
`TypeChip` Component 입니다. attrs 값을 조절하여 TypeChip 의 크기를 조정할 수 있습니다
- `app:iconSize="40dp"` : IconSIze
<image width = "500" src="https://github.com/user-attachments/assets/c23f500a-2864-4aa7-a70b-ee03a7cd2eb0"/>
- `app:emptyBackGround="false"` : 뒷배경이 없을 때
<image width = "500"  src="https://github.com/user-attachments/assets/ba822b9c-0261-4dbb-a27a-e8ed707a36ec"/>
- 여러가지 util 함수들을 몇개 추가했습니다. 보고 이해 안되시면 코멘트 남겨주세요!
`seriablizable`, `parcelable`, `withArgs`, 
이제 전 배포 및 모니터링 툴 다는걸 준비할게요!
=> [AN_UI] TypeChip component, CommonBindingAdapter, Serializable, Parcelable Util 함수들 추가

.github/workflows/Backend-CD.yml, backend/pokerogue/docker/nginx/conf.d/nginx.conf
> Issue Number: #79
저번 설정 파일에서 잘못되었던 부분
```bash
upstream was {
server http://server:8080;
keepalive 32;
}
```
고친 후 🥲
```bash
upstream was {
server server:8080;
keepalive 32;
}
```
=> [BE-FEAT] Nginx keepalive, log 설정 변경

.github/workflows/Backend-CD.yml, backend/pokerogue/docker/Dockerfile-fail2ban, backend/pokerogue/docker/Dockerfile-nginx, backend/pokerogue/docker/fail2ban/jail.local, backend/pokerogue/docker/fail2ban/paths-common.conf, backend/pokerogue/docker/nginx/conf.d/nginx.conf, backend/pokerogue/docker/nginx/nginx.conf
> Issue Number: #115 
---
`fail2ban`은 로그 텍스트 파일을 분석하여 `iptables`을 이용하여 네트워크 요청에 대한 필터링을 할 수 있도록 돕습니다.
`iptables`는 리눅스나 우분투에서 사용되는 유틸리티 프로그램입니다.
`iptables`를 사용하면 리눅스 커널의 방화벽 설정을 편하게 커스터마이징할 수 있습니다.
방화벽이란 결국 네트워크 패킷을 필터링하는 것이고, 심지어 패킷의 형태를 바꿀 수도 있고, 포트 매핑도 가능합니다.
도커에서 컨테이너를 사용할 때 호스트와 포트 매핑을 하는 경우가 많습니다. 
도커 역시 세부적으로는 `iptables`를 사용하고 있습니다.
`fail2ban`은 `iptables`를 조금 더 사용하기 쉽게 도와줍니다.
도커를 사용하는 저희 환경에서 `nginx`의 로그파일을 호스트 환경에 마운트 시키...
=> [BE-INFRA] 무작위 네트워크 공격 방지를 위한 fail2ban 추가

backend/pokerogue/src/test/java/com/pokerogue/environment/repository/RepositoryTest.java
> Issue Number: #127
아래와 같은 상황에서 쓰면 좋을 것 같습니다.
1) JPA 쿼리메소드(쿼리) 테스트
2) (조회) API 부하 테스트
3) AN이 `localhost`에서 사용할 테스트 환경
⚠️ 모든 팀원이 공유하는 테스트 db이기 때문에 데이터나 테이블 수정(`insert`, `delete`, `create table`, `truncate`)이 안됩니다. 설정 파일에 나와 있는 MySQL 유저로만 사용해주세요 !
⚠️ `RepositoryTest`만 profile을 `test`로 지정해놓았고, 나머지는 `local-mysql`로 두었습니다.
1) 노션의 Test DB 페이지에서 docker-compose.yml을 다운 받고 실행시킨다.
2) yml 파일을 test로 지정해서 테스트하거나 로컬 서버를 올린다. (테스트 코드는 `@ActiveProfiles` 사용)
=> [BE-INFRA] 쿼리 테스트 환경 구성

backend/pokerogue/src/main/java/com/pokerogue/helper/type/repository/PokemonTypeMatchingRepository.java, backend/pokerogue/src/test/java/com/pokerogue/helper/type/repository/PokemonTypeMatchingRepositoryTest.java
> Issue Number: #128 
- [] 있음
- Type.findAll, Type.findByName 은 개선할 점이 보이지 않았습니다.
- TypeMatching.findAll은 `Join fetch`를 사용하여 쿼리의 횟수를 줄였습니다.
- [개선 전 후 비교](https://github.com/woowacourse-teams/2024-pokerogue-helper/issues/128#issuecomment-2265316132)
=> [BE-REFACTOR] PokemonType 쿼리 개선 

backend/pokerogue/src/main/java/com/pokerogue/helper/ability/domain/PokemonAbility.java, backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java, backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java, backend/pokerogue/src/test/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepositoryTest.java, backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
> Issue Number: #125 
```
`findByIdWithPokemonMappings`를 `fetch Join` 하여 포켓몬 당 한번의 쿼리가 아닌,
해당 `ability`에 해당하는 값들을 전부 영속성 컨텍스트에 저장하도록 수정
```
유저가 1000명, 5번씩 동시에 요청하는 경우 (해당 `ability`에 해당하는 포켓몬이 49마리)
인 경우 약 7배의 차이가 생김
=> [BE-REFACTOR] PokemonAbility 쿼리 개선

android/app/build.gradle.kts, android/stringmatcher/build.gradle.kts
- closed #147 
- api 27~34까지 추가하였습니다.
- API levels 27 and higher 이상부터 추가할 수 있어서 27부터 34까지 추가했습니다.
- 사용법은 `./gradlew pixel4api30DebugAndroidTest`로 `device-name`과`BuildVariant`를 넣어주시면 됩니다.
- 한번에 모든 기기를 사용하고 싶으면 group name인 phones를 넣으시면 적용됩니다 !
=> [AN-Config] 테스트용 디바이스 추가

backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonRepository.java, backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java, backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/repository/PokemonRepositoryTest.java
> Issue Number: #155
- 포켓몬 도감 페이지 정렬은 쿼리로, 특성 상세 페이지 정렬은 서비스 코드로 진행했습니다 :)
=> [BE-FIX] 포켓몬 목록 조회 정렬 적용

backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java, backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java, backend/pokerogue/src/main/java/com/pokerogue/helper/type/domain/PokemonType.java, backend/pokerogue/src/test/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepositoryTest.java, backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java, backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/domain/PokemonTest.java
> Issue Number: #171, #169
PokemonTest 하려다보니 몇 엔티티 클래스에 `@AllArgsConstructor` 추가되었습니다. 테스트를 위한 생성자 추가에 반대하시는 분은 당근을 흔들어주세요 .. 🥕
=> [BE-FIX] 포켓몬이 없는 특성 상세 페이지 조회, 포켓몬 타입 정렬

android/app/src/main/res/layout-land/fragment_pokemon_detail.xml, android/gradle/libs.versions.toml
- closed #170 
[pokemon_detail_landscape.webm](https://github.com/user-attachments/assets/ee7d01ac-807d-43c2-9b58-a8ed81c3fee0)
- 포켓몬 상세 landscape
- 특성 디테일쪽이랑 똑같이 guideline 설정해서 만들었습니다.
- 데모데이 이후에 결정
=> [0.1.30-alpha/AN-FIX, AN_UI] 포켓몬 디테일 화면 가로 화면 대응

android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/boss/BiomeBossFragment.kt, android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/gym/BiomeGymFragment.kt, android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/wild/BiomeWildViewHolder.kt, android/app/src/main/res/layout/fragment_biome_boss_pokemon.xml, android/app/src/main/res/layout/fragment_biome_gym_pokemon.xml, android/app/src/main/res/layout/item_biome_next_biomes.xml, android/app/src/main/res/values/strings.xml, android/local/src/androidTest/java/poke/rogue/helper/local/entity/PokemonFixtures.kt
- closed #296 
[an:ui:바이옴디테일 (1.1.0) fix.webm](https://github.com/user-attachments/assets/d78c0eac-522b-4456-ae53-f833b6af78d0)
- 야생 포켓몬 탭에서 스크롤 시, 포켓몬의 크기가 작아지는 이슈 해결했습니다.
- 탭에 해당하는 데이터가 없을 시, empty view 추가 했습니다.
- 다음 바이옴 탭에서 이름과 이미지의 간격 수정하였습니다. 
- 그런 건 없어요~~
- biome detail toolbar 이름 수정
=> [1.1.0.alpha/AN-FIX] 바이옴 디테일 페이지 UI 수정

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt, android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeGuideActivity.kt, android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeUiEventHandler.kt, android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeViewModel.kt, android/app/src/main/java/poke/rogue/helper/presentation/biome/guide/BiomeGuideActivity.kt, android/app/src/main/res/drawable/ic_biome_map.xml, android/app/src/main/res/layout/activity_biome.xml, android/app/src/main/res/layout/activity_biome_detail.xml, android/app/src/main/res/layout/activity_biome_guide.xml, android/app/src/main/res/layout/item_biome_next_biomes.xml, android/app/src/main/res/values/strings.xml, android/app/src/test/java/poke/rogue/helper/presentation/biome/BiomeViewModelTest.kt
- close #304 
[an:feat:바이옴웹뷰구현.webm](https://github.com/user-attachments/assets/b5351321-6c93-49c8-ab11-968d3d307d20)
- toolbar의 제목을 바이옴 디테일에 해당하는 이름으로 변경했습니다.
- 바이옴 리스트 화면에서 깃발모양 클릭 시, 웹뷰로 이동하도록 추가했습니다.
- 그런건 없어요~
- 바이옴 검색 기능 구현
=> [1.1.0/AN_FEAT,AN_UI] 바이옴 전체 지도 toolbar에 웹뷰 구현 

android/app/src/main/java/poke/rogue/helper/presentation/battle/AnalyticsExtensions.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleNavigationHandler.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleSelectionUiState.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/model/SelectionData.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/model/SelectionMode.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/model/SkillSelectionUiModel.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/BattleSelectionActivity.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/BattleSelectionViewModel.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/SelectionStep.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/BattlePokemonTypesAdapter.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionFragment.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionViewHolder.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionFragment.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionViewModel.kt, android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/SelectableUiModel.kt, android/app/src/main/java/poke/rogue/helper/presentation/util/fragment/FragmentExtension.kt, android/app/src/main/java/poke/rogue/helper/presentation/util/view/ViewExtension.kt, android/app/src/main/res/layout/activity_battle.xml, android/app/src/main/res/layout/activity_battle_selection.xml, android/app/src/main/res/layout/fragment_skill_selection.xml
- closed #297
https://github.com/user-attachments/assets/4481e44d-5f8b-479f-92dc-87f8cf7839e8
생각보다,,, 변수가 많아서 조금 걸렸네용 🥹 
✅ 다른 영역 터치 시  키보드 내리기
-> 버튼 올리기 제외
✅ 포켓몬에 해당 하는 기술 불러오는 부분 오류 해결 
-> 이전에 선택했던 포켓몬 데이터를 불러오는 과정에서 꼬였었더라구요
✅ `기술` 선택 시 바로 `기술 선택` 페이지로 이동
-> 만약 선택된 데이터가 없는 경우에는 바로 포켓몬 선택으로 이동
-> 선택된 데이터가 있다면 바로 기술 선택으로!
✅ `registerForActivityResult` 로 리팩토링!
-> 액티비티 버전 문제가 해결되어서 다시 리팩토링 했습니당
살짝씩 깜빡거리는 부분이 있는것 같기는 한데 이런 부분들은 차차 개선해보도록 하겠습니당
- 로그 달기
- 기술 위력 정보 UI 개선
=> [1.1.0/AN_FIX] 배틀 디테일 로직 수정

android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/model/BattlePredictionUiModel.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionFragment.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionFragment.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionViewModel.kt, android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteBattleDataSource.kt, android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
- closed #313 #314 
-> 작업 단위가 작아서 두 개 이슈 합침 이슈
https://github.com/user-attachments/assets/8237680c-d13d-4132-a927-44552cef05dc
- 기술 위력이 마이너스 값일 경우, `-`로 표시
- 배수 값 별 색상 다르게 표시 ( 1 미만 : 회색 / 1 ~ 2 : 빨강 / 3 이상 : 초록)
- 이미 선택한 값이 있는 경우, 해당 위치로 스크롤해서 보여주기
- 중복 기술 값이 존재해서 일단 `distinct`로 방지해두었습니당
- 배틀 구도 정보 저장
=> [1.1.0/AN-FEAT] 배틀 선택 / 결과 UI 개선 

android/analytics/src/main/java/poke/rogue/helper/analytics/AnalyticsInitializer.kt, android/analytics/src/main/java/poke/rogue/helper/analytics/AnalyticsLogger.kt, android/app/src/main/java/poke/rogue/helper/PokeRogueHelperApp.kt
=> [1.1.0/AN_REFACTOR] APP 단의 FIrebase 초기화 코드 analytics 모듈로 이동

android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleSelectionsState.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionFragment.kt, android/data/src/main/java/poke/rogue/helper/data/datasource/LocalBattleDataSource.kt, android/data/src/main/java/poke/rogue/helper/data/model/PokemonWithSkillIds.kt, android/data/src/main/java/poke/rogue/helper/data/repository/BattleRepository.kt, android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt, android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt, android/data/src/main/java/poke/rogue/helper/data/repository/DexRepository.kt, android/gradle/libs.versions.toml, android/local/build.gradle.kts, android/local/src/main/java/poke/rogue/helper/local/datastore/BattleDataStore.kt, android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeDexRepository.kt
- closed #323
- PASS
- 내 포켓몬, 기술, 상대 포켓몬 선택 데이터 저장 기능 구현
- `Datastore`을 사용하여 해당 데이터들을 저장했습니다.
- 현재 skill ID 값으로 해당 skill 데이터를 불러오는 API 는 따로 없어서 일단 이 전에 불러왔던 skill들을 map 형식으로 캐싱해두고, 나중에 find를 활용하여 해당하는 Skill 데이터를 찾을 수 있도록 설정했습니다.
- `Dex Repository` 에서도 포켓몬 ID를 넘기면 해당 `Pokemon` 을 반환해주는 메서드도 추가했습니다!
-  기존에 있던 부분은 Detail을 반환하기 때문
=> [1.1.0/AN_FEAT] 배틀 선택 데이터 저장

.github/workflows/Backend-CD-Dev.yml, .github/workflows/Backend-CD-Prod.yml
> Issue Number: #346
이 PR 역시 다른 PR들보다 먼저 머지된다면 다른 PR이 개발 서버에 배포 돼도 오류 없이 MongoDB에 연결돼서 작동할 수 있습니다 🙂
=> [BE-INFRA] 개발 DB 서버 설정

.github/workflows/Backend-CD-Dev.yml
=> [BE-INFRA] 기존 디비 ec2에 있는 도커를 dev ec2안으로 옮긴다

android/local/src/main/java/poke/rogue/helper/local/dao/PokemonDao.kt, android/local/src/main/java/poke/rogue/helper/local/db/PokeRogueDatabase.kt
- closed #354 
그런 건 없어요~
-  룸 엔티티 변경에 대해 대응한다.
--- 
기존: 앱을 켤 때마다 항상 룸 DB 드롭하고 새로 만듭니다.
변경됨: 룸 엔티티의 정보가 바뀌었을 때만, 룸 DB 를 드롭하고 새로 만듭니다.
룸 AutoMigration 은 안 썼습니다.
이틀 삽질 엄청했는데 결과는 코드 3줄 넣으면 되는 거였네요 ㅋㅋㅋㅋㅋ
---
상황 설명을 드릴게요. 
1. 현재 구조: DB 에서 포켓몬 조회합니다.  비어있으면 서버로부터 요청하여 DB 에 포켓몬 데이터들을 저장합니다..
2. DB 엔티티에 backImageUrl 이 추가되었으니, DB 에 저장된 데이터들을 업데이트 해야 한다.
3. 즉, 우리는 서버로부터 받은 포켓몬 데이터를 다시 DB 에 저장해야 합니다.
방법1. 
그러러면, 전체 포켓몬 목록 API 를 호출해서 backImageUrl 을 필터링 한 다음에 DB 에 데이터를 직접 넣어주어야 합니다.
이렇게 하면 기존 DB 데이터들은 유지하고 새로 추가된 데이터만 DB 에 넣어줄 수 있습니다.
방법2. 
하지만 저는 그냥 룸 엔티티의 정보가 바뀌었을 때만, 룸 DB 를 드롭하고 새로 만들도록 구현했습니다.
1. 공수가 너무 많이 듭니다. 단순 엔티티가 하나 추가되었는데 기존에 있던 데이터 칼럼과 비교하고 필터링하고 다시 넣어주는 로직이 생깁니다.
2. 만약 다음에 또 다른 엔티티가 추가된다고 하면, 일일이 다시 로직을 수정해야주어야 합니다.
1. 공수가 적게 든다.
2. 캐시된 데이터의 손실이 큰 문제가 되지 않는다.
글쎄요..?
일단 미션 좀 하고 내일 팀원들에게 의견 …
=> [1.1.0/AN-FEAT] 룸 엔티티 수정 대응(destructive-recreation)

.github/workflows/Backend-CD-Dev.yml, .github/workflows/Backend-CI.yml, backend/pokerogue/src/main/java/com/pokerogue/helper/data/PokemonValidator.java, backend/pokerogue/src/main/java/com/pokerogue/helper/move/controller/MoveController.java, backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveFlag.java, backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveTarget.java, backend/pokerogue/src/main/java/com/pokerogue/helper/move/dto/MoveDetailResponse.java, backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonRepository.java, backend/pokerogue/src/test/java/com/pokerogue/helper/move/repository/MoveRepositoryTest.java, backend/pokerogue/src/test/java/com/pokerogue/helper/move/service/MoveServiceTest.java
> Issue Number: #359 
우선 이 정보가 들어가면 되겠지 하고 짠 코드입니다.
추가로 기존에 존재하던 api와 중복 문제 때문에 임시로 api를 대충 만들었는데 어떻게 할 지 정해야 될 것 같아요
=> [BE-FEAT] 기술 관련 api 만들기

backend/pokerogue/src/main/java/com/pokerogue/PokerogueApplication.java, backend/pokerogue/src/main/java/com/pokerogue/helper/biome/controller/BiomeController.java, backend/pokerogue/src/main/java/com/pokerogue/helper/biome/converter/SortingCriteriaRequestConverter.java, backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/NativePokemon.java, backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/Tier.java, backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java, backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java, backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DataMongoDbConfig.java, backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/WebConfig.java, backend/pokerogue/src/main/java/com/pokerogue/helper/global/constant/SortingCriteria.java, backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/ErrorMessage.java, backend/pokerogue/src/test/java/com/pokerogue/environment/controller/ControllerTest.java, backend/pokerogue/src/test/java/com/pokerogue/environment/repository/MongoRepositoryTest.java, backend/pokerogue/src/test/java/com/pokerogue/helper/biome/controller/BiomeControllerTest.java, backend/pokerogue/src/test/java/com/pokerogue/helper/biome/service/BiomeServiceTest.java, backend/pokerogue/src/test/java/com/pokerogue/helper/biome/service/NativePokemonComparatorTest.java, backend/pokerogue/src/test/java/com/pokerogue/helper/global/constant/SortingCriteriaTest.java
> Issue Number: #362
이건 제안인데요! 쿼리 스트링으로 보스 포켓몬과 야생 포켓몬들 티어 정렬 기준을 받도록 api를 수정하면 어떨까요? 사용자 활동 로그를 바탕으로 정렬 순서도 고치기로 했던 걸로 기억하는데 정렬 같은 조건문은 요구사항에 따라 바뀌는 것보다 이렇게 설계하는게 더 유연해보여서 제안합니다 :)
`보스 포켓몬들에 대해 티어 높은 순으로 정렬`만 요구사항이었기 때문에 쿼리스트링 default 값을 보스 포켓몬은 desc, 야생 포켓몬은 asc로 설정해보았습니다. (하위 호환성 O)
별로라면 철회하겠읍니다..
=> [BE-REFACTOR] 바이옴 포켓몬 티어 정렬

android/app/src/main/java/poke/rogue/helper/PokeRogueHelperApp.kt, android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt, android/app/src/main/java/poke/rogue/helper/presentation/splash/PokemonIntroViewModel.kt, android/data/src/main/java/poke/rogue/helper/data/datasource/LocalDexDataSource.kt, android/data/src/main/java/poke/rogue/helper/data/datasource/LocalVersionDataSource.kt, android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteVersionDataSource.kt, android/data/src/main/java/poke/rogue/helper/data/di/DataSourceModule.kt, android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt, android/local/src/androidTest/java/poke/rogue/helper/local/dao/PokemonDaoTest.kt, android/local/src/main/java/poke/rogue/helper/local/dao/PokemonDao.kt, android/local/src/main/java/poke/rogue/helper/local/datastore/VersionDataStore.kt, android/local/src/main/java/poke/rogue/helper/local/di/DataStoreModule.kt, android/remote/src/main/java/poke/rogue/helper/remote/di/ServiceModule.kt, android/remote/src/main/java/poke/rogue/helper/remote/dto/response/version/VersionResponse.kt, android/remote/src/main/java/poke/rogue/helper/remote/injector/ServiceModule.kt, android/remote/src/main/java/poke/rogue/helper/remote/service/VersionService.kt
- closed#381
- 아직 서버쪽 api가 완성 안돼서 터짐! 서버 api 완성되면 머지 후 바아로 release할 예정!
=> [1.1.0/AN-FEAT] Splash 화면에서 포켓몬 데이터 캐싱 교체 전략 추가

backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DataMongoDbConfig.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonInMemoryRepository.java, backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> Issue Number: #419 
> yml 파일 수정, 단일 포켓몬 정보 오류 수정, MongoConfig 수정
--------
- 포켓로그 전세계 실시간 사용자 수: 약 6000명
- 1%를 웃도는 100명으로 VUser 및 TPS 설정
- k6로 100 VUser로 1분 간 부하 테스트
- 모든 데이터는 평균값으로 통계
- 서비스 핵심 기능 API로 테스트
- max thread 값은 10으로 설정한다. 5도 높은 TPS 값을 가지지만 CPU 사용율 측면에서 10이 유리하다.
- 포켓몬 목록 조회 API는 캐싱을 사용하기 때문에 배틀 API로만 성능을 측정한다.
- maxSize는 가장 TPS가 높은 10으로 설정한다.
- minSize와 maxSize를 동일하게 설정해서 connection pool 이점을 최대한 활용한다.
- waitingTime은 WAS 대기 시간보다 작은 값(2초)으로 설정한다. (default: 2분)
=> [BE-INFRA] Tomcat thread pool 및 MongoDB connection pool 설정

.github/workflows/Backend-CD-Prod-A.yml, .github/workflows/Backend-CD-Prod-All.yml, .github/workflows/Backend-CD-Prod-B.yml, backend/pokerogue/build.gradle
> Issue Number: #398 
](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-jobs-in-a-workflow) 성공 여부에 의존적이도록 코드를 짠다. + 아까 삭제했던 트리거를 이 곳에 추가한다.
[무중단 배포](https://eugenedev.notion.site/129f528177ee800d9c89c19a421e1b03) 테스트까지 완료하여 실제 배포 브랜치로 변경을 요청합니다. 
(CD실행 후 끝나기까지 0.01초 간격으로 get요청을 보내도 성공적으로 결과 반환)
=> [BE-INFRA] 무중단 배포 be/release로 브랜치 변경

android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
https://github.com/user-attachments/assets/8b61ded3-1f86-489e-81e5-0aba273f2f17
데모데이 때 필터링, 정렬, 검색 시 Scroll 최상단으로 안올라가니까 많이 불편하더라구요!  
그래서 빠르게 반영~
- 그건 새롭게 스프린트 시작되면? 결정하는걸루
=> [1.1.1/AN-feat] PokemonList 화면에서 필터링, 정렬, 검색 시 Scroll 최상단으로 올리기

android/build.gradle.kts, android/gradle/libs.versions.toml, android/local/build.gradle.kts, android/local/schemas/poke.rogue.helper.local.db.PokeRogueDatabase/1.json, android/local/schemas/poke.rogue.helper.local.db.PokeRogueDatabase/2.json, android/local/schemas/poke.rogue.helper.local.db.PokeRogueDatabase/3.json, android/local/src/androidTest/java/poke/rogue/helper/local/database/PokeRogueDatabaseMigrationTest.kt, android/local/src/androidTest/java/poke/rogue/helper/local/utils/MigrationTestUtils.kt, android/local/src/main/java/poke/rogue/helper/local/db/PokeRogueDatabase.kt, android/local/src/main/java/poke/rogue/helper/local/db/migrations/Migration1To2.kt, android/local/src/main/java/poke/rogue/helper/local/di/DataBaseModule.kt, android/local/src/main/java/poke/rogue/helper/local/entity/PokemonEntity.kt
데모데이 때 `Migration_1_to_2 Exception`이 문제가 생겼던 이유는 제가 Koin 적용할 때 [fallbackToDestructiveMigrationFrom()](https://developer.android.com/reference/kotlin/androidx/room/RoomDatabase.Builder#fallbacktodestructivemigrationfrom)을 추가를 안해줘서 그렇습니다.. 하하 미안합니다 😢  
- DB Auto Migration 작업 및 Migration 테스트 
- DB Migration 테스트 
`fallbackToDestructiveMigration` 은 db가 마이그레이션에 실패하면 Drop하고 다시 만드는 함수입니다.(심지가 저번에도 설명해주었지만)
따라서, DB 마이그레이션한 이력이 남지 않습니다.  과거 DB 버전으로 회귀하고 싶을 경우와 같이 버전 기록이 필요한 경우가 생기면, 과거 PR 이력들을 모두 찾지 않는 이상 불가능합니다.
이제 시간에 쫓겨 작업하지 않아도 되니, Migration 작업이 조금 번거로워도 더 좋은 프로젝트가 되기 위해 제안해봅니다!
> 디비 마이그레이션 테스트에 대한 이해를 위해 간단하게 작성해둘게여
> 테스트 코드를 작성하는 방법은 작성한 코드를 봐주세여~
`room-test`에서 지원하는 `MigrationTestHelper` 가 scheme history를 기반으로 마이그레이션 테스트합니다.
따라서, `androidTest/schemas/../pokeRogueDatabase/(dbVersion).json` 에 …
=> [1.1.1/AN-feat] DB 마이그레이션 (Drop 방식 X)

.github/ISSUE_TEMPLATE/새로운-기능.md, .github/workflows/Auto_Close_Issue.yml, .github/workflows/Backend_Auto_Create_PR.yml, .github/workflows/Issue_Checkbox_Notification.yml
> Issue Number: #445 
[BE-FEAT] 이슈 템플릿 수정했습니다!
전부 러프하게 작성해서 제대로 예외 처리가 안 되어 있어 차차 리팩토링이 필요하긴 합니다.
추가로 이슈 close파일이랑 pr생성 파일은 해당 브랜치에 존재하지 않으면 작동을 안 해서 be/develop과 an/develop에도 추가해야 할 듯 합니다.
be/ 로 시작되는 브랜치에 push가 발생하면 해당 브랜치의 이름에서 이슈 번호를 추출해 pr을 만듭니다. 이때 해당 이슈의 Task 항목부터 Time항목 전까지 가져와서 pr에 넣습니다.
지금은 be/로 시작하면 무조건 작동하기 때문에 be/feat, be/refactor ,... 과 같은 브랜치에서만 push가 발생하면 작동하도록 수정할 예정입니다.
pr의 내용에서 #뒤에 있는 숫자에 해당하는 이슈들을 자동으로 close합니다. 이 워크플로우는 pr이 머지되거나 close되면 동작합니다.
백엔드 이슈 템플릿에서 Client 항목에 있는 체크박스 중 하나라도 체크가 되면 디스코드 안드 채널로 알림을 보냅니다.
이슈가 생성되거나 수정되면 동작합니다.
지금은 이슈가 생성되면 무조건 동작합니다. 다만 이슈에 Client항목이 없으면 동작하지 않기 때문에 큰 문제는 없을 듯 합니다.
=> [ALL] 워크플로우 파일 추가

android/app/src/main/res/layout/activity_pokemon_list.xml
- closed #450
https://github.com/user-attachments/assets/3c307c24-51e2-4340-8930-d6790c1b2713
`HeaderGroup` : AppBar + PokeChips
- Scoll UP 시: `HeaderGroup` Collapse
- Scoll Down 시: `HeaderGroup` Show
- 이렇게 쉽게 되다니.. 너무 슬픕니다 ㅜㅜ 심지 고마워요!
=> [1.2.0/AN-UI] 포켓몬 리스트 스크롤 시 Appbar, PokeChips Collapse 애니메이션 적용

android/build.gradle.kts, android/gradle/libs.versions.toml
- 불필요한 legacy인 `buildScript`를 걷어냄
- 우리 프로젝트 Gradle 버전: 8.4 
Gradle 7.0 이상에서는 `buldScript`  대신 `plugins`와 `pluginManagement` 를 사용해서 플러그인 의존성을 관리하라고 나와있습니다.  
제가 초기에 프로젝트 설정할 때, 이에 대한 지식이 부족해서 2가지 방식 모두 중복 적용했었네요 🥲  
두 방식의 차이를 궁금해하실까봐 간략하게 설명 남기겠습니다.
```kotlin
buildscript {
repositories {
google()
mavenCentral()
}
dependencies {
classPath(libs.agp)
}
}
apply(plugin = "com.android.application") // 플러그인 수동 적용
```
`buildscript`는 Gradle이 빌드 스크립트를 실행하기 전에, 필요한 플러그인 의존성을 먼저 클래스패스에 추가하는 역할을 했습니다.
다운 받을 `repository`와 classPath를 지정해준 후, apply를 통해 플러그인을 적용했습니다.
```kotlin
// settings.gradle.kts
pluginManagement {
repositories {
google()
mavenCentral()
gradlePluginPortal()
}
}
// build.gradle.kts
plugins {
alias(libs.plugins.android.application) apply false
}
```
-  `pluginManagement`를 통해 plugin을 어느 …
=> [1.2.0/AN-Config] Project 단 build.gradle.kts 에서 buildScript 문 삭제

android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt, android/app/src/main/res/anim/fade_in.xml, android/app/src/main/res/anim/fade_out.xml, android/app/src/main/res/drawable/ic_arrow_up_24.xml, android/app/src/main/res/layout/activity_pokemon_list.xml
- closed #475
https://github.com/user-attachments/assets/8a919d1f-c1f8-4ce7-bc32-bb6d33f50a11
1) 리사이클러뷰 스크롤 시 이벤트 처리를 ViewModel에서 담당할까 했지만, 서버와의 통신이나 검증 로직이 들어갈 일이 없다 판단하여 Activity 에 버튼 show/hide 로직을 작성하였습니다!
2) 스크롤이 완전히 종료 후 `300ms` 정도 후에 버튼을 hide 처리했습니다. 시간이 너무 짧거나 길면 말씀해주세요 😉  
에뮬레이터로 테스트하면 너무 빨리 없어져보일 수도?!
- 포켓몬 폼 형태 이름 중복해서 보이는 문제 해결
- 버튼 클릭 시 Scale UP 애니메이션 구현
=> [1.2.0/AN-UI] PokemonList 스크롤 최상단으로 올리는 버튼

android/stringmatcher/build.gradle.kts
X
- `java.toolchain` → `sourceCompatibility`,` targetCompatibility` 방식으로 마이그레이션
기존 `java.toolchain` 방식은 Gradle이 어떤 JDK 버전으로 `컴파일` 할지를 명시적으로 지정합니다.
결과적으로, 빌드 환경 자체를 JDK 17로 `강제`하게 됩니다.
이로 인해 해당 프로젝트를 사용하는 모든 개발자는 Gradle이 사용하는 **JDK를 반드시 17로 설치**를 요구하는 제약이 있습니다.
제 로컬에는 JDK 17이 설치되어 있지 않아, 빌드 시 다음과 같은 오류가 발생했습니다.
우리의 목적은 .class 파일을 Java `17` 바이트코드로 생성하는 것이지,
JDK 17 설치 자체를 강제하려는 건 아닙니다.
JDK 17 이상의 환경이라면 하위 호환이 가능하므로,
`sourceCompatibility / targetCompatibility` 방식이 더 유연한 선택이라 판단해 마이그레이션했습니다.
참고1). `sourceCompatibility` : 어떤 Java 문법 버전까지 허용할지
참고2). `targetCompatibility` : 어떤 버전의 .class 바이트코드를 생성할지
JDK 17 설치를 강제하기보다는,
하위 호환 가능한 컴파일 설정으로 유연하게 대응하기 위해 마이그레이션했습니다.
[sourceCompatibility, targetCompatibility, and JVM toolchains in Gradle explained](https://stefma.medium.com/sourcecompatibility-targetco …
=> [1.2.1/ AN-CONFIG] :stringmatcher java 설정 변경

android/data/src/main/java/poke/rogue/helper/data/model/Pokemon.kt
- closed #477 
- as is
- to be
- 포켓몬 폼 형태 이름 중복해서 보이는 문제가 있었음
- 서버에서 폼 이름 붙여서 보내주고 있음
=> [1.2.1/AN-Fix] 포켓몬 폼 형태 이름 중복해서 보이는 문제 해결

android/app/src/main/res/values-ko-rKR/strings.xml, android/app/src/main/res/values/strings.xml
- closed #506 
작업 이전: 
작업 후:
- 문제 원인: 
- 국제화를 적용하면서 리소스를 찾을 때 우선순위가 바뀌어서 아래와 같은 일이 벌어졌습니다.
- strings.xml 의 우선순위 문제 떄문에 Manifest 에서 앱 이름을 선택할 때  `app/src/alpha/res/values/strings.xml` 나 `app/src/debug/res/values/strings.xml` 등을 선택하지 않고 `app/src/main/res/values-ko-rKR/strings.xml` 혹은 `app/src/main/res/values/strings.xml` 를 선택.
- 해결 방법:
- app_name 에 대해서 app/src/alpha/res/values/strings.xml 혹은 app/src/main/res/values-ko-rKR/strings.xml 를 참조하지 않도록 위 파일들의 app_name 스트링 리소스 제거.
- 그런건 없어요~
- API 통신 시 헤더에 로케일 정보 넣어서 보내기
=> [1.2.1/AN-FIX] 앱 이름 구분을 위한 스트링 리소스 편집

android/analytics/src/main/java/poke/rogue/helper/analytics/FireBaseAnalyticsLogger.kt
- closed #이슈넘버
- 로그 찍히는거 확인
-  Crashlytics 로그 안찍히는 이슈 해결
- message가 null 인 경우에 crashlytics 로그를 찍고 있어서 수정
- tmi). 회사에서 crashlytics `recordException()`이랑 `log()`  찍을 일이 있어서 포케로그로 먼저 테스트해봤는데.. 잘못 찍고 있더라구요 그래서 수정했습니다!
- 1.2.1 릴리즈하기
=> [1.2.1/AN-FIX] Crashlytics 로그 안찍히는 이슈 해결
