woowacourse-teams/2024-pokerogue-helper

- .gitmodules
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/controller/PokemonController.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonType.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonTypeMapping.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokemonResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonRepository.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/domain/PokemonType.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/domain/Type.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/util/dto/ApiResponse.java
> Issue Number: #1 
- 이슈에 있는 태스크 들을 붙여넣어주세요.
```
```
> [BE-FEAT] 포켓몬 리스트 불러오는 API 

- backend/pokerogue/src/main/java/com/pokerogue/helper/article/controller/ArticleController.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/article/domain/Article.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/article/dto/ArticleResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/article/repository/ArticleRepository.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/article/service/ArticleService.java
> [BE-FEAT] 꿀팁 리스트 불러오는 API

- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/domain/PokemonAbility.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/PokemonAbilityResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonTypeMapping.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokedexResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokemonResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/domain/PokemonType.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonTypeResponse.java
> Issue Number: #41
dto 및 테이블 필드명 변경
> [BE-FEAT] 수정 요청 사항 반영

- .github/workflows/Backend-CD.yml
- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/domain/PokemonAbility.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DatabaseInitializer.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonAbilityMapping.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonTypeMapping.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonAbilityMappingRepository.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonTypeMappingRepository.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/domain/PokemonType.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/repository/PokemonTypeRepository.java
> Issue Number: #39
(추가) CD 스크립트 트리거 `push`로 제한 (아무리 테스트 삼아 하더라도 pr로 하면 배포가 너무 자주되는 것 같아..)
도메인 클래스에 생성자들 추가했는데 봐주십시오 !!
테스트 환경은 다음 이슈에서 진행하겠습니다~
> [BE-FEAT] 개발 DB 초기 데이터 삽입

- backend/pokerogue/src/main/java/com/pokerogue/helper/type/controller/PokemonTypeController.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/service/PokemonTypeService.java
> [BE-FEAT] 타입 리스트를 불러오는 API

- backend/pokerogue/src/main/java/com/pokerogue/helper/article/controller/ArticleController.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/article/dto/ArticleDetailsResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/article/service/ArticleService.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/ErrorMessage.java
> [BE-FEAT] 단일 꿀팁 상세 정보를 불러오는 API

- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityActionHandler.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityActivity.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityAdapter.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityUiEventHandler.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityViewHolder.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityViewModel.kt
- android/app/src/main/res/layout/activity_ability.xml
- android/app/src/main/res/layout/item_ability_description.xml
- closed #64 
- 기존과 동일하여 영상은 첨부하지 않았습니다 !
- `View Model & Data Binding` 적용
- `Flow` 적용
- 데이터와 관련된 부분은 해커톤 이후 수정하지 않았습니다 ! 다음 이슈에서 네트워크 연결을 하면서 수정하도록 하겠습니다.
- pr단위가 너무 작은 것 같네요..!
- 특성 정보를 불러오는 api와 통신
> [AN_REFACTOR] 특성 화면 MVVM 패턴 적용

- backend/pokerogue/src/main/java/com/pokerogue/helper/type/controller/PokemonTypeController.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonMatchingAndTypeResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonMatchingResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/service/PokemonTypeService.java
> [BE-FEAT] 타입 상성 리스트를 불러오는 API

- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java
> Issue Number: #74 
- 동작하지 않는 API 수정 (단일 특성 조회)
- JPQL문 수정
> [BE-FIX] 단일 특성 조회 API 쿼리문 수정

- backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/dto/pokemon/PokemonDetail.java
- backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/parser/DtoParser.java
- backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
- backend/pokerogue/src/main/java/com/pokerogue/external/s3/service/S3Service.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/PokemonAbilityResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/PokemonAbilityWithPokemonsResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/SameAbilityPokemonResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DatabaseInitializer.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonAbilityMapping.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokedexResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokemonResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonTypeResponse.java
> Issue Number: #72 
Dto필드 이름 name에서 koName으로 변경
height, weight 자료형 double로 변경
> [BE-FEAT] 1차 배포 대비 수정사항 반영

- android/app/src/main/java/poke/rogue/helper/data/datasource/RemoteAbilityDataSource.kt
- android/app/src/main/java/poke/rogue/helper/data/model/Ability.kt
- android/app/src/main/java/poke/rogue/helper/data/repository/AbilityRepository.kt
- android/app/src/main/java/poke/rogue/helper/data/repository/DefaultAbilityRepository.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityActivity.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityAdapter.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityUiModel.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityViewHolder.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityViewModel.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailActivity.kt
- android/app/src/main/java/poke/rogue/helper/presentation/ability/model/AbilityUiModel.kt
- android/app/src/main/java/poke/rogue/helper/remote/dto/response/ability/AbilityResponse.kt
- android/app/src/main/java/poke/rogue/helper/remote/service/AbilityService.kt
- android/app/src/main/res/layout/activity_ability_detail.xml
- android/app/src/main/res/layout/item_ability_description.xml
- closed #62 
[an:feat:특성(네트워크연결).webm](https://github.com/user-attachments/assets/66750717-4d64-467d-a2bdbfac24073aa1)
아직 특성에 대한 설명은 api 미완성 !
- 특성 목록을 `네트워크`를 통해 데이터 로드 (기존에는 dummy)
- `레포지토리`, `데이터 소스` 추가
- dto -> data -> ui 매핑
- 현재 특성 api가 바뀌고 있는 것 같아서, 체크아웃 해서 실행시키면..🫣
이름을 통해 특성 검색
> [AN-FEAT] 특성 목록 네트워크 연결 

- backend/pokerogue/docker/nginx/conf.d/nginx.conf
- backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DatabaseInitializer.java
> [BE-FEAT] Nginx 설정 최적화

- .github/workflows/Android_PR_Builder.yml
- .gitignore
- android/.gitignore
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/poke/rogue/helper/remote/RetrofitModule.kt
- android/app/src/main/java/poke/rogue/helper/remote/interceptor/RedirectInterceptor.kt
- android/app/src/main/res/xml/network_security_config.xml
- android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
- closed #92 
Thanks to @jongmee 
개발 편의성을 위해 미아가 준 docker script `android/docker` 넣어두었습니다!  
따라서, gitignore 도 추가 설정해두었으니 참고하세요!
- 파베 설정
- 초성 검색
> [AN-CONFIG] 개발 서버 다운시 Local host 로 리다이렉션

- .github/actions/add_labels/action.yml
- .github/actions/reviewers.yml
- .github/workflows/Android_PR_Builder.yml
- closed #95
PR Open 할 때!
- AN_CONFIG 🧭, AN_FEAT ✨, AN_FIX 🐛, AN_REFACTOR ✍️, AN_UI 🎨, AN_CI/CD🤖
- pr open 하면 자동으로 Reviewers, Assignees, label 이 지정됩니다.
이때 PR 의 제목을 기반으로 label을 부여하기 때문에  PR 을 만드실 때  
제목에 `refactor, feat, ui, refactor, fix, config, ci, cd` 을 포함해서 적어주셔야합니다! 
- 이제 진짜 초성 검색 구현할게유 ㅋㅋ
Thanks to @kkosang
> [AN_CI] PR Open 될 때 reviewers, assignees, labels 자동 할당 

- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/PokemonAbilityController.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/article/controller/ArticleController.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/PokemonExceptionHandler.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/controller/PokemonController.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> Issue Number: #108 
- 이슈에 있는 태스크 들을 붙여넣어주세요.
```
핸들링 에러 추가
1. NullPointerException
2. DataAccessException
3. OutOfMemoryError
4. Exception
```
나머지 이슈 태스크들은 PR을 나누어 올릴 예정입니다!
> [BE-REFACTOR] Log 상세화하여 추가적으로 찍기 및 핸들링 할 에러 추가

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
- android/app/src/main/java/poke/rogue/helper/presentation/tip/TipActivity.kt
- android/app/src/main/res/layout/activity_tip.xml
- closed #99 
[Screen_recording_20240731_173830.webm](https://github.com/user-attachments/assets/336e80b8-6886-4273-984c-5c614e4dabc4)
- 기존 크롬창 연결 대신 웹뷰로 구현
- 이 후에 앱바 커스텀 구현할 예정이라 일부러 앱바는 넣지 않았습니다!
- 쉽다~
- 앱바 커스텀
> [AN-FEAT] 꿀팁 웹뷰 구현

- android/app/src/test/java/poke/rogue/helper/presentation/ability/AbilityViewModelTest.kt
- android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModelTest.kt
- android/testing/build.gradle.kts
- android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepository.kt
- android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
- closed #121 
영상은 패스~
- 특성 페이지 `FakeRepository & ViewModel Test`
- 특성 상세 페이지  `ViewModel test`
- 해당 페이지 작업할 때 같이 했어야 하는데 지금 올립니다..!
가로 화면 대응 !!
> [AN-FEAT] 특성 ViewModel Test

- .github/workflows/Backend-CD.yml
- .github/workflows/Backend-CI.yml
- backend/pokerogue/src/test/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepositoryTest.java
- backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
> [BE-REFACTOR] CI를 self-hosted runner로 변경

- backend/pokerogue/src/test/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepositoryTest.java
- backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
- backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/service/PokemonServiceTest.java
> Issue Number: #138 
```
1. 일치하지 않는 경로 수정
2. Id 변화에 종속적이지 않도록 테스트 수정
3. `Long.MaxValue` 를 사용하여 테스트 하도록 수정
```
> [BE-FIX] 테스트 경로 수정

- backend/pokerogue/docker/fail2ban/jail.local
- backend/pokerogue/docker/nginx/conf.d/nginx.conf
- backend/pokerogue/docker/nginx/nginx.conf
- backend/pokerogue/src/test/java/com/pokerogue/helper/type/repository/PokemonTypeMatchingRepositoryTest.java
> [BE-REFACTOR] NGINX limt_req 모듈 설정 변경

- backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/client/PokeClient.java
- backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/dto/Language.java
- backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/dto/Name.java
- backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/parser/DtoParser.java
- backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/type/repository/PokemonTypeRepository.java
- backend/pokerogue/src/test/java/com/pokerogue/environment/client/FakePokeClient.java
> Issue Number: #143 
한글 이름이 없을시 영어 저장
도트 이미지 없을시 아트 이미지 저장
> [BE-REFACTOR] 내용이 없을 때 저장하는 값 수정

- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> fix: 스트림 콜렉팅 중복 키 에러 핸들링

- android/app/src/main/java/poke/rogue/helper/PokeRogueHelperApp.kt
> [0.1.2-alpha/AN-FEAT] Firebase Dev, Alpha 버전 로깅 툴 해제

- .github/workflows/Backend-CD.yml
- .github/workflows/Backend-CI.yml
> [BE-INFRA] CI, CD에서 사용하는 docker compose 설정 파일 버전 관리

- android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
- android/app/src/main/res/layout-land/activity_type.xml
- 포켓몬 상세 페이지에서 홈버튼 작동 안됬던 부분 해결
- 상성 가로 화면 '+' 이미지 추가
-
> [0.1.3-alpha/AN-FIX] 홈화면 이동 기능 수정

- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
- backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
> [BE] 3차 스프린트 데모데이 CD 시연 준비

- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
- backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
`같은 특성을 가진 포켓몬 목록을 조회할 때 id 순으로 정렬`하지 못하는 오류 수정
> [BE] 3차 스프린트 CD 시연

- backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> Issue Number: #247
getter 하나 수정했습니다~
> [BE-FIX] 기술 리스트에서 카테고리 로고 이미지 누락

- backend/pokerogue/src/main/java/com/pokerogue/external/s3/service/S3Service.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/biome/dto/BiomePokemonResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/biome/dto/BiomePokemonTypeResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/biome/dto/BiomeResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/biome/dto/BiomeTypeResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/biome/dto/NextBiomeResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/biome/dto/TrainerPokemonResponse.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> Issue Number: #269 
Dto 반환값 수정, 타입 로고 확장자 제거
> [BE-REFACTOR] 바이옴 타입 전달 시 이름과 함께 전달

- .gitignore
- android/.gitignore
- android/analytics/build.gradle.kts
- android/app/build.gradle.kts
- android/app/proguard-rules.pro
- android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailActivity.kt
- android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonAdapter.kt
- android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
- android/app/src/main/java/poke/rogue/helper/presentation/dex/model/PokemonUiModel.kt
- android/app/src/main/java/poke/rogue/helper/ui/component/PokeChip.kt
- android/app/src/main/res/layout/activity_home.xml
- android/data/src/main/java/poke/rogue/helper/data/model/Pokemon.kt
- android/gradle/libs.versions.toml
- android/remote/src/main/java/poke/rogue/helper/remote/dto/response/pokemon/PokemonResponse2.kt
- android/remote/src/test/java/poke/rogue/helper/remote/service/AbilityServiceTest.kt
- android/remote/src/test/res/ability.json
[fix: idx로 hashID](https://github.com/woowacourse-teams/2024-pokerogue-helper/commit/e992385c231293f9c5a5c35bcb0dbe64aa63239f)
[chore: 바이옴에서 포켓몬 상세페이지 이동 일단 막기](https://github.com/woowacourse-teams/2024-pokerogue-helper/commit/fffef1d037726d7594a9a612414214d8fc95da45)
[chore: 포켓몬 리스트에서 포켓몬 상세페이지 이동 일단 막기](https://github.com/woowacourse-teams/2024-pokerogue-helper/commit/34a16de3f0b227413c70b1db03822989d76591f4)
[fix: PokeChip spec이 null일 때 처리](https://github.com/woowacourse-teams/2024-pokerogue-helper/commit/cb3f1fb16eef5f7e798107954b7ebf2f5710686b)
[feat: item도감, 꿀팁 도감 삭제(주석처리)](https://github.com/woowacourse-teams/2024-pokerogue-helper/commit/eab5fdf12955604b376dced6e658be5434aee58e)
[build: 1.0.1으로 버전업](https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/280/commits/2c7f0270 …
> [1.0.0/AN/Release]

- backend/pokerogue/src/main/java/com/pokerogue/helper/ability2/config/AbilityDatabaseInitializer.java
> [BE-FIX] 특성 파일 오류 수정

- backend/pokerogue/src/main/java/com/pokerogue/helper/ability2/config/AbilityDatabaseInitializer.java
- backend/pokerogue/src/test/java/com/pokerogue/helper/battle/DataInitializerTest.java
> [BE-FIX] 데이터 수정

- backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleMove.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> Issue Number: #293
immune은 날씨 데미지에 대한 immune이라 일단 제외시켰습니다 ! ex. 땅 타입은 모래 바람에 immune이 있음
> [BE-FIX] 배틀 결과 계산에서 날씨 배수 조건 추가

- .github/workflows/Android_Develop_PR_CD.yml
- 제곧내 
Pullrequest가 닫힐 때 CD가 되도록 변경
> [1.1.0/AN_CI] develop PR Ci, CD 분리

- android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt
- android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeQueryHandler.kt
- android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeSearchViewBindingAdapter.kt
- android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeViewModel.kt
- android/app/src/main/res/layout/activity_biome.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/test/java/poke/rogue/helper/presentation/biome/BiomeViewModelTest.kt
- android/data/src/main/java/poke/rogue/helper/data/repository/BiomeRepository.kt
- android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBiomeRepository.kt
- android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeBiomeRepository.kt
- closed #309
[an:ui:바이옴리스트(검색).webm](https://github.com/user-attachments/assets/e8bffc4a-c532-4478-af00-e89788219d1d)
- 바이옴 리스트에서 이름으로 검색
- 키보드 영역외 터치시 키보드 내리기
- 리싸이클러뷰 변경시 맨위로 스크롤 올리기
- 그런 건 없어요 ~
> [1.1.0/AN_FEAT] 바이옴 리스트 검색 기능 구현

- backend/pokerogue/src/test/java/com/pokerogue/environment/repository/MongoRepositoryTest.java
> Issue Number: #333
이슈 코멘트와 본문을 읽어주세요! 기본 생성자 추가는 각자 하는게 충돌이 안 날 것 같아 제가 하지 않았습니다.
MongoRepositoryTest를 extends 하고 테스트하고자하는 MongoRepository를 @Autowired 해서 사용하시면 됩니다. 추후를 위해 추가해놓는게 좋을 것 같아 공유해요~!
> [BE-TEST] MongoRepository 뼈대 테스트 코드 추가

- .github/workflows/Backend-CI.yml
> Issue Number: #339
CI 워크플로우에 테스트용 MongoDB를 설정한다
깜빡 잊었던 CI 🥲 남아 있던 MySQL 싹 제거하고 (예전에 호환성 때문에 계속 남겨두다가 잊음) Mongo로 교체했습니당
> [BE-TEST] CI에 테스트용 MongoDB 설정

- backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveFlag.java
> [BE-FIX] MoveFlag 추가

- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonInMemoryRepository.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> Issue Number: #396
목표 TPS 달성을 위해 포켓몬 데이터를 인메모리에 캐싱하고 새벽 5시마다 리프레시 하도록 일단 조치했습니다.
> 포켓몬 데이터 캐싱

- .github/workflows/Backend-CD-Prod-A.yml
- .github/workflows/Backend-CD-Prod-All.yml
- .github/workflows/Backend-CD-Prod-B.yml
- backend/pokerogue/build.gradle
> Issue Number: #398 
](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-jobs-in-a-workflow) 성공 여부에 의존적이도록 코드를 짠다. + 아까 삭제했던 트리거를 이 곳에 추가한다.
> [BE-INFRA] 무중단 배포 구현에 따른 action 스크립트 변환

- .github/workflows/Android_Develop_CD.yml
- .github/workflows/Android_Develop_CI.yml
- .github/workflows/Android_Release_CD.yml
- .github/workflows/Android_Release_CI.yml
- closed #이슈넘버
- Android Dev CI 스크립트를 Android Dev CD 스크립트에서 재사용하도록 리팩토링
- Android Release CI 스크립트를 Android Release CD 스크립트에서 재사용하도록 리팩토링
- 플레이스토어 자동 배포
> [1.1.0/AN-Config] Android CI/CD WorkFlow 최적화,  플레이스토어 자동 배포

- android/app/src/main/java/poke/rogue/helper/di/ViewModelModule.kt
- android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt
- android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeViewModel.kt
- android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailActivity.kt
- android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailViewModel.kt
- android/app/src/test/java/poke/rogue/helper/presentation/biome/BiomeActivityTest.kt
- android/app/src/test/java/poke/rogue/helper/presentation/biome/BiomeViewModelTest.kt
- android/app/src/test/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailActivityTest.kt
- android/app/src/test/java/poke/rogue/helper/presentation/di/TestViewModelModule.kt
- android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBiomeRepository.kt
- android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeBiomeRepository.kt
- closed #410 
그런건 없어요~
-  바이옴 리스트 화면 Koin 적용 및 테스트
- 바이옴 상세 화면 Koin 적용 및 테스트
-
> [1.1.1/AN-REFACTOR] 바이옴(리스트,상세)화면 의존성 Koin 적용

- .github/workflows/Backend-CD-Prod-All.yml
트리거가 [merge_group](https://docs.github.com/ko/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#merge_group) 로 되어 있어 변경합니다!
> [BE-INFRA] cd 워크플로우 트리거 이벤트 변경

- backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/EvolutionResponse.java
> Issue Number: #442 
이미지 url 수정 및 진화 조건 수정
> [BE-HOTFIX] 이미지 url이 전송이 안 되는 오류 수정

- backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/AbilityService.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
- backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/ImageUrl.java
> [BE-FIX] 바이옴 및 트레이너 이미지 url 수정

- .github/workflows/PR_Comment_Notification.yml
#444 에서 삭제된 `PR_Comment_Notification.yml` 워크플로우 파일 복구
> PR Comment Notification workflow 복구

- android/gradle/libs.versions.toml
> Android v1.2.0 Develop 반영
